[ko]
  languageName = "Korean"
  contentDir = "content/ko"
  weight = 10
  [en.params]
    languageISO = "ko"
    languageTag = "ko-KR"
    footer = 'DRZG Docs'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
