media: docs/media
content:
  - name: guide_drzg
    label: 다램지굴
    path: docs/guide/drzg
    type: collection
    format: yaml-frontmatter
    fields:
      - name: title
        label: 제목
        type: string
        required: true
      - name: description
        label: 설명
        type: string
      - name: weight
        label: 순서
        type: number
        default: 0
      - name: body
        label: 본문
        type: text  # markdown이 아닌 text
        required: true
    filename: '{fields.title}.md'
    view:
      primary: title
      fields: [title, description, weight]
      sort: [weight, title]
      
  - name: guide_drz
    label: 다램지
    path: docs/guide/drz
    type: collection
    format: yaml-frontmatter
    fields:
      - name: title
        label: 제목
        type: string
        required: true
      - name: description
        label: 설명
        type: string
      - name: weight
        label: 순서
        type: number
        default: 0
      - name: body
        label: 본문
        type: text  # markdown이 아닌 text
        required: true
    filename: '{fields.title}.md'
    view:
      primary: title
      fields: [title, description, weight]
      sort: [weight, title]

  - name: patch_notes
    label: 패치노트
    path: docs/patch
    type: collection
    format: yaml-frontmatter
    fields:
      - name: title
        label: 제목
        type: string
        required: true
      - name: date
        label: 날짜
        type: date
        required: true
      - name: description
        label: 요약
        type: string
      - name: authors
        label: 작성자
        type: string
        list: 
          min: 1
          max: 5
          default: ["다램지"]
      - name: categories
        label: 카테고리
        type: select
        list:
          min: 1
          max: 3
          default: ["다램지굴"]
      - name: body
        label: 본문
        type: text
        required: true
    filename: '{fields.title}.md'
    view:
      primary: title
      fields: [title, date, description, categories]
      sort: [date:desc, title]
