[build]
  publish = "public"
  functions = "functions"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.17.0"
  NPM_VERSION = "10.9.2"
  HUGO_VERSION = "0.148.1"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false
