backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "docs"
    label: "문서"
    folder: "content/docs"
    create: true
    slug: "{{slug}}"
    nested: { depth: 5 }
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "설명", name: "description", widget: "string" }
      - { label: "요약", name: "summary", widget: "string", required: false }
      - { label: "Lead", name: "lead", widget: "string", required: false }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "최종 수정일", name: "lastmod", widget: "datetime" }
      - { label: "초안", name: "draft", widget: "boolean", default: false }
      - { label: "가중치", name: "weight", widget: "number", default: 10 }
      - { label: "목차", name: "toc", widget: "boolean", default: true }
      - { label: "내용", name: "body", widget: "markdown" }

  - name: "info"
    label: "정보"
    folder: "content/info"
    create: true
    slug: "{{slug}}"
    nested: { depth: 5 }
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "설명", name: "description", widget: "string" }
      - { label: "요약", name: "summary", widget: "string", required: false }
      - { label: "Lead", name: "lead", widget: "string", required: false }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "최종 수정일", name: "lastmod", widget: "datetime" }
      - { label: "초안", name: "draft", widget: "boolean", default: false }
      - { label: "가중치", name: "weight", widget: "number", default: 10 }
      - { label: "목차", name: "toc", widget: "boolean", default: true }
      - { label: "내용", name: "body", widget: "markdown" }

  - name: "patch"
    label: "패치노트"
    folder: "content/patch"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "설명", name: "description", widget: "string" }
      - { label: "요약", name: "summary", widget: "string", required: false }
      - { label: "Lead", name: "lead", widget: "string", required: false }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "최종 수정일", name: "lastmod", widget: "datetime" }
      - { label: "초안", name: "draft", widget: "boolean", default: false }
      - { label: "가중치", name: "weight", widget: "number", default: 10 }
      - { label: "기여자", name: "contributors", widget: "list", required: false }
      - { label: "태그", name: "tags", widget: "list", required: false }
      - { label: "카테고리", name: "categories", widget: "list", required: false }
      - { label: "고정", name: "pinned", widget: "boolean", default: false }
      - { label: "홈페이지 표시", name: "homepage", widget: "boolean", default: false }
      - { label: "내용", name: "body", widget: "markdown" }
