[[main]]
  name = "문서"
  url = "/docs/빠른-시작"
  weight = 10

[[main]]
  name = "정보"
  url = "/info/"
  weight = 20

[[main]]
  name = "패치노트"
  url = "/patch/"
  weight = 30

[[sidebar_docs]]
  name = "빠른 시작"
  pageRef = "/docs/quickstart"
  weight = 10

[[sidebar_docs]]
  name = "다램지굴"
  pageRef = "/docs/drzg/"
  weight = 20

[[sidebar_docs]]
  name = "다램지"
  pageRef = "/docs/drg/"
  weight = 30

[[social]]
  name = "Discord"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-discord" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M8 12a1 1 0 1 0 2 0a1 1 0 0 0 -2 0"></path><path d="M14 12a1 1 0 1 0 2 0a1 1 0 0 0 -2 0"></path><path d="M8.5 17c0 1 -1.356 3 -1.832 3c-1.429 0 -2.698 -1.667 -3.333 -3c-.635 -1.667 -.476 -5.833 1.428 -11.5c1.388 -1.015 2.782 -1.34 4.237 -1.5l.975 1.923a11.913 11.913 0 0 1 4.053 0l.972 -1.923c1.5 .16 3.043 .485 4.5 1.5c2 5.667 2.167 9.833 1.5 11.5c-.667 1.333 -2 3 -3.5 3c-.5 0 -2 -2 -2 -3"></path><path d="M7 16.5c3.5 1 6.5 1 10 0"></path></svg>'
  url = "https://discord.drzg.win"
  weight = 20

[[footer]]
  name = "다램지굴"
  url = "https://drzg.win"
  weight = 10

[[footer]]
  name = "디스코드"
  url = "https://discord.drzg.win"
  weight = 10
